### ISSUE TITLE
Firepad example userlist: FirepadUserList is not defined

### ISSUE THREAD

**Issue by bjorno43** [FirebaseExtended/firepad#289]
Running the example returns FirepadUserList is not defined. Doing a small bit of research reveales that it's missing firepad-userlist.js. However, including it returns `ref.root()` is not a function on line 12

**Comment by wildeyes** [comment]
:(

**Comment by mikelehen** [comment]
To be clear, you're using this code (https://github.com/FirebaseExtended/firepad/blob/master/examples/userlist.html) and it's not working?

**Comment by wildeyes** [comment]
Yes.

**Comment by mikelehen** [comment]
Weird.  It works just fine for me (I just clone the firepad repo and open the userlist.html file in a browser and I get a working userlist on the left).

If you're still having issues, please provide the exact steps you're taking.  Thanks!

**Comment by arisgiavris** [comment]
encountering this as well.

**Comment by arisgiavris** [comment]
Sorry.
I used only this code: (https://github.com/FirebaseExtended/firepad/blob/master/examples/userlist.html)
Now work perfectly!
