### ISSUE TITLE
Firepad CodeMirror example not using any color-coded syntax.

### ISSUE THREAD

**Issue by crono009** [FirebaseExtended/firepad#320]
Hi all, not sure if this is the place to report this question but I couldn't really find anything to explain why this doesn't work. I'm not sure if the example on Firepad.io is incomplete or if I am missing something else. 

I created a new Visual Studio project and tried running the Code Editing (CodeMirror) example shown at this link: https://firepad.io/examples/ . It runs fine, however I don't have any of the nice color-coded syntax as it does on the firepad example.

To clarify, in the example, the word "function" should be highlighted purple, however on my project all the text is simply black. It is as if I am using Notepad rather than a code editor. Any ideas why this would be the case?

The first image below represents what it should look like, the second image is what it looks like on my new project. 

![image](https://user-images.githubusercontent.com/28131759/50367740-1b3f8a80-0537-11e9-9d6c-dbaaf979fedc.png)

![image](https://user-images.githubusercontent.com/28131759/50367750-272b4c80-0537-11e9-8a19-fdfe537a4c79.png)

Thanks!

**Comment by mikelehen** [comment]
What code are you using to initialize CodeMirror?  Notice the 'mode' option used in that example:

```
      var codeMirror = CodeMirror(document.getElementById('firepad-container'), {
        lineNumbers: true,
        mode: 'javascript'
      });
```

**Comment by crono009** [comment]
Turns out I was missing this :

> <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.17.0/mode/javascript/javascript.js"></script>

Thanks for leading me in the right direction!
