### ISSUE TITLE
Firepad gets focus automatically

### ISSUE THREAD

**Issue by siddug** [FirebaseExtended/firepad#321]
Hi guys,

We have few firepad elements in a long page and they are automatically grabbing focus and thus causing the page to scroll the firepad element. Is there anything we can do to avoid this?

### Version info

**Firebase:** 3.3.0

**Firepad:** 1.4.0

**Ace:** None

**CodeMirror:** 5.39.0

**Other (e.g. Node, browser, operating system) (if applicable):** Chrome, Windows

### Steps to reproduce

A page with firepad element in it.

### Expected behavior

Firepad shouldn't automatically get focus of the site and scroll to the element.

### Actual behavior

Firepad grabs the focus to the editor and scrolls down to the element

**Comment by mikelehen** [comment]
Sorry, I don't know of any reason this would happen.  Can you provide a minimal repro?

**Comment by avrahamzvv** [comment]
maybe on ready can use
firepad.codeMirror_.focus();
