### ISSUE TITLE
Using Firepad text editor and CodeMirror at the same time causes code-colored syntax in text editor.

### ISSUE THREAD

**Issue by crono009** [FirebaseExtended/firepad#326]
I am developing an app where the user has the choice to either use Firepad for text editing or CodeMirror for code editing. It seems when I load both on the same page, the syntax based coloring for the code editor also applies to the Text Editor for certain keywords like 'With' and 'Do'. What is the correct way to approach this issue in order to allow the user to use both the Code editor and the text editor?

To replicate this, I combined the code from example 1 and 2 from the following link below onto one page with different variable names so the two editors get created independently. Everything works as intended except for the color-coded syntax getting applied to the text editor: https://firepad.io/examples/#-tYeIcwROhE

To be clear, this still happens even if I create a separate html file with only the text editor.

Here's the image of what I see on my text editor. Thanks in advance for your help!

![image](https://user-images.githubusercontent.com/28131759/51856138-c89a8080-22e3-11e9-809b-cb853b0554d7.png)

**Comment by crono009** [comment]
For more information: I found out that this script is the reason why the keywords in the text editor look like code:
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.17.0/mode/javascript/javascript.js"></script>

However I need this script in order to create a javascript code editor alongside the text editor on the same page. Would someone know a work around for this or are these two text/code editors just not compatible with each other?

**Comment by corwin-of-amber** [comment]
Seems like this is not happening anymore. At least the examples page seems fine to me.
