### ISSUE TITLE
Obtain history

### ISSUE THREAD

**Issue by MJRomka** [FirebaseExtended/firepad#328]
I use Firepad with CodeMirror. Is there a way to obtain operations history? Do you have some builtin functions or I have to query and parse it on my own?

**Comment by mikelehen** [comment]
Nothing builtin, sorry.  The history is stored as a list of operations in Firebase.  The easiest way to display a past point in the history would be to just copy the history up to the point you want to keep into a new Firebase location and then point Firepad at that.  Another developer wrote a short blog post about doing that here: https://masonwebdev.wordpress.com/2016/05/09/how-history-is-stored-in-firebase-using-firepad/
