### ISSUE TITLE
Table Support

### ISSUE THREAD

**Issue by boutsak** [FirebaseExtended/firepad#337]
We are trying to implement table support into Firepad. 
We have already achieved that by using arbitrary "entities"(eg https://github.com/FirebaseExtended/firepad/blob/448aca7c5148716200645be7d117e74d34b0c668/lib/firepad.js#L520) , but after inserting the table into Firepad, the table cells are not editable. I cannot find any way to do that so the user can edit the cells content, any recommendation? 

Thank you in advance

**Comment by mikelehen** [comment]
Sorry, table support is outside the scope of what firepad can support. To make it collaborative and editable you'd need a whole new set of OT operations, etc.
