### ISSUE TITLE
Get full text from Firebase

### ISSUE THREAD

**Issue by strig** [FirebaseExtended/firepad#338]
Sorry, this isn't an issue but I can't find a good answer to this question elsewhere. 

Is there a way to get the full text content directly from Firebase, either via the Firebase API or through the Firebase cloud functions? I see that there is a headless mode for Node project, unfortunately I'm not using Node in my project. 

I see that the content in Firepad is stored as a sequence of edits, what would I have to do to get the full text from this sequence? I'm using Python if that makes a difference.

**Comment by mikelehen** [comment]
To do it without using headless mode you'd need to replay the history of operations to compute the resulting text.  There's a ruby example here you could try to model: https://github.com/FirebaseExtended/firepad/blob/master/examples/firepad.rb
