### ISSUE TITLE
Bullet list style is broken with the latest CodeMirror

### ISSUE THREAD

**Issue by ktsn** [FirebaseExtended/firepad#348]
### Version info

**Firebase:** 7.6.1

**Firepad:** 1.5.3

**CodeMirror:** 5.50.2

### Test case

https://jsfiddle.net/ktsn/6L03sdqn/4/

### Steps to reproduce

See the bullet list style and its markup.
Each item does not have enough indentation on left side. In addition, `second level` and `third level` is actually second and third level nesting (`firepad-li-2`, `firepad-li-3`) respectively but there is no style difference.

Looks like CodeMirror has padding style with `.CodeMirror pre.CodeMirror-line, .CodeMirror pre.CodeMirror-line-like` on the latest version and it overwrites firepad indentation style.

### Expected behavior

There are proper indentation padding for each item.

### Actual behavior

No indentation padding.

**Comment by mikelehen** [comment]
Should be fixed by https://github.com/FirebaseExtended/firepad/commit/b7aa36d40a431172815e0b9658f0a19221e7f545 which is released as v1.5.9.

**Comment by ktsn** [comment]
Thank you! I confirmed it on my app.
