### ISSUE TITLE
[Feature Request] Audioplayer and clickable time stamps in editor field

### ISSUE THREAD

**Issue by NiklasFoP** [FirebaseExtended/firepad#349]
Dear Firepad Community,

I have to following feature idea:
- adding an audio file and playing it in the firepad
- adding time stamps in the editor that can be clicked so that the player jumps to that position in the audio file

I don't think this feature exists yet. Is someone interested in working on this?

Thank you,
Niklas

**Comment by samtstern** [comment]
@NiklasFoP thanks for sharing your idea!  Firepad is stable now and we're not adding new large features anymore, so I am going to close this issue.  If you do intend to work on this the best thing to do would be fork the library.
