### ISSUE TITLE
fromMonaco broken since release 1.5.4

### ISSUE THREAD

**Issue by luminaxster** [FirebaseExtended/firepad#353]
### Version info

**Firebase:**
^7.11.0

**Firepad:**
1.5.4 to 1.5.9

**Ace:**

**CodeMirror:**

**Monaco:**
^0.20.0

**Other (e.g. Node, browser, operating system) (if applicable):**
Node 8.3.11, React Create App 2.0
### Test case

Firepad.fromMonaco(firebaseRef, monacoEditor);

### Steps to reproduce

just calling the method causes an error, using Webpack via React App.
### Expected behavior

create a Firepad using Monaco

### Actual behavior

Error:
<img width="1089" alt="Screen Shot 2020-03-15 at 8 01 42 PM" src="https://user-images.githubusercontent.com/6577822/76714068-7260ea80-66fb-11ea-8d19-6b2789d279fc.png">

A change was made to the file lib/monaco-adapter.js after release 1.5.3, the defect is still in version 1.5.9:
<img width="1028" alt="Screen Shot 2020-03-15 at 8 24 32 PM" src="https://user-images.githubusercontent.com/6577822/76714069-7260ea80-66fb-11ea-876b-ab53411e2338.png">

Thank you! Great work on the library!
Update: addressed in pull requests #356 and #351 and fix will be part of release 1.5.10.

**Comment by samtstern** [comment]
`1.5.10` has been released!
