### ISSUE TITLE
Updating the way Firebase is imported

### ISSUE THREAD

**Issue by luminaxster** [FirebaseExtended/firepad#358]
The following lines cause trouble in production:

https://github.com/FirebaseExtended/firepad/blob/master/lib/firebase-adapter.js#L6
https://github.com/FirebaseExtended/firepad/blob/master/lib/headless.js#L20

They throw the following warning:
<img width="443" alt="Screen Shot 2020-03-27 at 8 32 50 PM" src="https://user-images.githubusercontent.com/6577822/77810318-41bd7100-706a-11ea-83ae-583e5dd38220.png">

Based on the previous files Firebase usage, the following change will remove the warning:
```
firebase = require('firebase/app');
require('firebase/database');
```

**Comment by samtstern** [comment]
@luminaxster thanks for reporting this!  Would you like to submit a Pull Request with the fix>
