### ISSUE TITLE
How to use firepad with  java script spread sheet?

### ISSUE THREAD

**Issue by webmarts2019** [FirebaseExtended/firepad#364]
Hi
I want to create a collaborative spreadsheet using firepad and javascript spreadsheet library, data table plugin.
So I wish to know. How can use the core features of firepad and change the editor from ACE or CodeMirror to javascript spreadsheet library?.

Thanks

**Comment by samtstern** [comment]
@webmarts2019 that's a big question and it's not something we can help you with inside a GitHub issue. This issue tracker is for specific firepad bugs.
