### ISSUE TITLE
latest version is not available from CDN

### ISSUE THREAD

**Issue by toasterpic** [FirebaseExtended/firepad#365]
### Version info

**Firepad:** 1.5.10

### Steps to reproduce and Test case

get https://cdn.firebase.com/libs/firepad/1.5.10/firepad.css
get https://cdn.firebase.com/libs/firepad/1.5.10/firepad.min.js

### Expected behavior

works

### Actual behavior

404 for anything past 1.5.3

**Comment by mikelehen** [comment]
We moved the releases to firepad.io instead of cdn.firebase.com, so you can grab it from e.g. https://firepad.io/releases/v1.5.10/firepad.css

**Comment by toasterpic** [comment]
Hi @mikelehen, appreciate the speedy reply! May I suggest updating the README as well?

**Comment by samtstern** [comment]
@toasterpic want to send a PR to update the README?
