### ISSUE TITLE
Monaco Adapter Bug - Multi-Change Event Errors

### ISSUE THREAD

**Issue by BrChung** [FirebaseExtended/firepad#380]
### Version info

**Firebase: v5.5.4**

**Firepad: v1.5.10**

**Monaco Editor: v0.20.0**

### Test case

Used provided Monaco example file `examples/monaco.html`

### Steps to reproduce

Perform any multi-change operation in Monaco Editor

Undo Example:
- Press the `backspace` key twice, then `Ctrl + Z` to undo

![undo](https://user-images.githubusercontent.com/35940686/93005878-8484df80-f50a-11ea-8753-f95d09639f9c.gif)

Drag Text Example:
- Highlight a text selection, and drag to a new location

![text move](https://user-images.githubusercontent.com/35940686/93005881-89e22a00-f50a-11ea-9de7-4bea3e0171ca.gif)

### Expected behavior

The document should be kept in sync with the Firebase database. Operations such as undo and dragging text should work as expected and changes should reflect on the database.

### Actual behavior

Undo Example:

![Screen Shot 2020-09-12 at 3 17 14 PM](https://user-images.githubusercontent.com/35940686/93005926-1f7db980-f50b-11ea-84fd-dd67886bd81c.jpg)

Drag Text Example:

![Screen Shot 2020-09-12 at 3 16 52 PM](https://user-images.githubusercontent.com/35940686/93005930-23a9d700-f50b-11ea-8f1b-3a26a9ac9a4e.jpg)

**Comment by samtstern** [comment]
Fixed by #381
